### ISSUE TITLE
Is `varint-compression` unmaintained?

### ISSUE THREAD

**Issue by KisaragiEffective** [nilsmartel/varint-compression#1]
Hello, thank you for your implementations!

I've typed `cargo add varint-compression` to pull your code, but it seems that you have renamed it to `vbyte-compression` in following commit:
https://github.com/nilsmartel/vbyte-compression/commit/90a0b4966b6c116c41dda07ca53c9ecabc50b994

Would I need to switch `vbyte-compression`? Would you consider `varint-compression` is deprecated and/or not maintained anymore?

**Comment by nilsmartel** [comment]
Hey, sorry for the late answer!

You're right, this is the currently maintained version
